name: composite actions test

on:
  push:

jobs:
  composite-action:
    name: job to test a composite action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chechout@v4
      - uses: ./
        id: compositAction 
        with:
          number1: 4
          number2: 2
      - run: echo ${{step.compositAction.output.result }}
      
      
