name: composite actions test

on:
  push:

jobs:
  composite action:
    name: job to test a composite action
    runs-on: ubuntu-lates
    steps:
      - uses: actions/chechout@v4
      - uses: ./ # this meaning using the root level of our repository and search for action file
        id: compositAction #add an id for this step
        with:
          number1: 4
          number2: 2
      - run: echo ${{step.compositAction.output.result }}
      
      
